const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",

  //user
  CHANGE_LANGUAGE:"CHANGE_LANGUAGE",
  CHANGE_PATH:"CHANGE_PATH",
  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",

  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",
  //Gender
  FETCH_GENDER_START:"FETCH_GENDER_START",
  FETCH_GENDER_SUCCSESS:"FETCH_GENDER_SUCCSESS",
  FETCH_GENDER_FAILD:"FETCH_GENDER_FAILD",
  
  CREATE_USER_SUSSESS:"CREATE_USER_SUSSESS",
  CREATE_USER_FAILD:"CREATE_USER_FAILD",

  DELETE_USER_SUSSESS:"DELETE_USER_SUSSESS",
  DELETE_USER_FAILD:"DELETE_USER_FAILD",

  EDIT_USER_SUSSESS:"EDIT_USER_SUSSESS",
  EDIT_USER_FAILD:"EDIT_USER_FAILD",

  //do an
  //categories
  FETCH_CATEGORIES_SUCCSESS:"FETCH_CATEGORIES_SUCCSESS",
  FETCH_CATEGORIES_FAILD:"FETCH_CATEGORIES_FAILD",
  //-create
  CREATE_CATEGORIES_SUSSESS:"CREATE_CATEGORIES_SUSSESS",
  CREATE_CATEGORIES_FAILD:"CREATE_CATEGORIES_FAILD",
  //-delete
  DELETE_CATEGORIES_SUCCSESS:"DELETE_CATEGORIES_SUCCSESS",
  DELETE_CATEGORIES_FAILD:"DELETE_CATEGORIES_FAILD",
  //-update
  UPDATE_CATEGORIES_SUCCSESS:"UPDATE_CATEGORIES_SUCCSESS",
  UPDATE_CATEGORIES_FAILD:"UPDATE_CATEGORIES_FAILD",

  //Food
  FETCH_FOODSALE_SUCCSESS:"FETCH_FOODSASLE_SUCCSESS",
  FETCH_FOODSALE_FAILD:"FETCH_FOODSASLE_FAILD",
  
  FETCH_FOOD_SUCCSESS:"FETCH_FOOD_SUCCSESS",
  FETCH_FOOD_FAILD:"FETCH_FOOD_FAILD",
  //-create
  CREATE_FOOD_SUSSESS:"CREATE_FOOD_SUSSESS",
  CREATE_FOOD_FAILD:"CREATE_FOOD_FAILD",
  //-delete
  DELETE_FOOD_SUCCSESS:"DELETE_FOOD_SUCCSESS",
  DELETE_FOOD_FAILD:"DELETE_FOOD_FAILD",
  //-update
  UPDATE_FOOD_SUCCSESS:"UPDATE_FOOD_SUCCSESS",
  UPDATE_FOOD_FAILD:"UPDATE_FOOD_FAILD",

  //SET_SELECTED_FOOD
  SET_SELECTED_FOOD:"SET_SELECTED_FOOD",
  //Order
  SET_SELECTED_ORDER:"SET_SELECTED_ORDER",
  //manage
  FETCH_CUSTOMER_FAILD:"FETCH_CUSTOMER_START",
  FETCH_CUSTOMER_SUCCSESS:"FETCH_CUSTOMER_SUCCSESS",
  //lấy phần tử cat được chọn
  SET_SELECTED_CAT:"SET_SELECTED_CAT",

  //cart
  ADD_TO_CART : 'ADD_TO_CART',
  REMOVE_FROM_CART : 'REMOVE_FROM_CART',
  UPDATE_CART_ITEM : 'UPDATE_CART_ITEM',
  SET_CART_ITEMS:"SET_CART_ITEMS",
  REMOVE_FROM_CART_ALL:"REMOVE_FROM_CART_ALL",
  PAY_BILL_SUCCSESS:"PAY_BILL_SUCCSESS",
  PAY_BILL_FAILD:"PAY_BILL_FAILD",
  //order
  FETCH_ORDER_SUCCSESS:"FETCH_ORDER_SUCCSESS",
  FETCH_ORDER_FAILD:"FETCH_ORDER_FAILD",
  FETCH_ORDERDETAIL_SUCCSESS:"FETCH_ORDERDETAIL_SUCCSESS",
  FETCH_ORDERDETAIL_FAILD:"FETCH_ORDERDETAIL_FAILD",
  UPDATE_ORDER_STATUS_SUCCSESS : 'UPDATE_ORDER_STATUS_SUCCSESS',
  UPDATE_ORDER_STATUS_FAILD : 'UPDATE_ORDER_STATUS_FAILD',
  DELETE_ORDER_SUCCSESS:"DELETE_ORDER_SUCCSESS",
  DELETE_ORDER_FAILD:"DELETE_ORDER_FAILD",
  //comment
  FETCH_ORDERCOMMENT_SUCCSESS:"FETCH_ORDERCOMMENT_SUCCSESS",
  FETCH_ORDERCOMMENT_FAILD:"FETCH_ORDERCOMMENT_FAILD",
  FETCH_COMMENT_SUCCSESS:"FETCH_COMMENT_SUCCSESS",
  FETCH_COMMENT_FAILD:"FETCH_COMMENT_FAILD",
  CREATE_COMMENT_SUCCSESS:"CREATE_COMMENT_SUCCSESS",
  CREATE_COMMENT_FAILD:"CREATE_COMMENT_FAILD",
  DELETE_COMMENT_SUCCSESS:"DELETE_COMMENT_SUCCSESS",
  DELETE_COMMENT_FAILD:"DELETE_COMMENT_FAILD",
  //payment
  LOADING_PAYMENT_SUCCSESS:"LOADING_PAYMENT_SUCCSESS",
  LOADING_PAYMENT_FAILD:"LOADING_PAYMENT_FAILD",
  //size
  LOADING_SIZE_SUCCSESS:"LOADING_SIZE_SUCCSESS",
  LOADING_SIZE_FAILD:"LOADING_SIZE_FAILD",
  //feedback
  CREATE_FEEDBACK_SUCCSESS:"CREATE_FEEDBACK_SUCCSESS",
  CREATE_FEEDBACK_FAILD:"CREATE_FEEDBACK_FAILD",
  FETCH_FEEDBACK_SUCCSESS:"FETCH_FEEDBACK_SUCCSESS",
  FETCH_FEEDBACK_FAILD:"FETCH_FEEDBACK_FAILD",
  DELETE_FEEDBACK_SUCCSESS:"DELETE_FEEDBACK_SUCCSESS",
  DELETE_FEEDBACK_FAILD:"DELETE_FEEDBACK_FAILD",
  //Thống kê
  FETCH_GETTOTAL_SUCCSESS:"FETCH_GETTOTAL_SUCCSESS",
  FETCH_GETTOTAL_FAILD:"FETCH_GETTOTAL_FAILD",

  FETCH_GETTOTALORDER_SUCCSESS:"FETCH_GETTOTALORDER_SUCCSESS",
  FETCH_GETTOTALORDER_FAILD:"FETCH_GETTOTALORDER_FAILD",
  
  FETCH_GETTOTALCATEGORY_SUCCSESS:"FETCH_GETTOTALCATEGORY_SUCCSESS",
  FETCH_GETTOTALCATEGORY_FAILD:"FETCH_GETTOTALCATEGORY_FAILD",
  
  FETCH_GETTOTALTIME_SUCCSESS:"FETCH_GETTOTALTIME_SUCCSESS",
  FETCH_GETTOTALTIME_FAILD:"FETCH_GETTOTALTIME_FAILD",
});

export default actionTypes;
